### ISSUE TITLE
Regions don't get updated when switching layout

### ISSUE THREAD

**Issue by banglashi** [meteorhacks/flow-layout#1]
Hi @arunoda,

I noticed that if you switch layout after login/logout of a user like described in issue #38 of flow-router the regions don't get rendered. You can find a demo project here: https://github.com/banglashi/flow-router-regions-update

I just added

``
FlowLayout._updateRegions(regions);
``
to line 20 in layout.js and this seems to fix the issue. But I think there is a better way to do it. Perhaps you could take a look?

**Comment by djhi** [comment]
:+1: I have the same prb

**Comment by arunoda** [comment]
Okay. I will fix this today.

**Comment by arunoda** [comment]
Okay. Check now.
I fixed the bug and publish a new version.
see commit: c98c02c

**Comment by banglashi** [comment]
Hi @arunoda,

thanks, that did the trick.

**Comment by arunoda** [comment]
Nice.

**Comment by djhi** [comment]
Thx @arunoda :)
