### ISSUE TITLE
#__flow-root messing with semantic:ui

### ISSUE THREAD

**Issue by wI2L** [meteorhacks/flow-layout#10]
Hello arunoda,

This `__flow-root` div is very problematic for me.
I am using `semantic:ui-css` in my project, and in order to have a nice sidebar, my main layout looks like this:

```
<template name="appLayout">
    {{> navbarTemplate}}
    {{> menubarTemplate}}
    <div class="app pusher">
        {{> ddpNotificationTemplate}}
        {{> sidebarTemplate}}
        <div id="page">
            <div class="inner">
                {{> Template.dynamic template=main}}
            </div>
        </div>
    </div>
</template>
```

Because of the `__flow-root` div, my layout is fucked up.

```
"Sidebar:" "Had to add pusher element. For optimal performance make sure body content is inside a pusher element" semantic_ui-css.js:11806:10
"Sidebar:" "Had to move sidebar. For optimal performance make sure sidebar and pusher are direct children of your body tag" <div class="ui sidebar left" id="menubar">
```
I dont really understand the need of this div element, but it is sure that is does not fit at all with a specific layout design like mine where elements placement matters.

Best regards,

Will

**Comment by wI2L** [comment]
Could it be possible to make it optionnal ?

Global or per render:

`FlowLayout.noWrapper()`
`FlowLayout.render(..., true)`

**Comment by wI2L** [comment]
In the meantime, as a workaround (a bit ugly tho), i defined in my `main.html`

```
<head>
    ...
</head>
<body id="__flow-root">
</body>
```

**Comment by LuisHerranz** [comment]
I am having the same issue with materializecss.

The workaround works but now we have a non used div there.

![screen shot 2015-04-13 at 13 22 27](https://cloud.githubusercontent.com/assets/3305402/7114715/71034db8-e1e0-11e4-8cd0-b38f41aa610e.png)

I think FlowLayout should check if there is already an element with "__flow-root" id before creating it.

**Comment by wI2L** [comment]
@LuisHerranz i agree
@arunoda any thought ?

As another solution, FlowLayout should let the developper specify as an optionnal argument, the `id` of the element to render in.

**Comment by Streemo** [comment]
@arunoda @wI2L @LuisHerranz I was about to make a similar issue. I have the same problem as well! Glad to know many of us have this problem.

If possible, it would be nice if the wrapper could be optional, or would first look in the client folder for a user-specified one, for example:

If I specify a __flow-root for the root element:
    don't use the default one, use mine.
else:
    use the default one provided in the flow layout source.

Do you guys know a way to include the flow-layout package simply without the "root.html" file? Then we can simply specify our own __flow-root element.

**Comment by wI2L** [comment]
@Streemo I found no solution but using the `root.html` file and specifiying the `__flow-root` element manually.
@arunoda Are you against the idea of providing an option to specify the root element manually or to disable it ro render inside body ? I would gladly make a complete PR with tests and doc if you are OK.

**Comment by churcho** [comment]
I also have the same issue. @arunoda  any chance we can get a workaround soon?

**Comment by arunoda** [comment]
Okay. I've figure out an API to set the root node.
See: https://github.com/meteorhacks/flow-layout#set-different-root-node

Hope this helps.

**Comment by LuisHerranz** [comment]
Perfect!  :+1:

**Comment by wI2L** [comment]
@arunoda Thanks you very much !

**Comment by arunoda** [comment]
Thanks.
