### ISSUE TITLE
api naming

### ISSUE THREAD

**Issue by trusktr** [meteorhacks/flow-layout#11]
Just an idea, but instead of

```
<template name="layout1">
  {{> Template.dynamic template=top}}
  {{> Template.dynamic template=main}}
</template>
```

maybe

```
<template name="layout1">
  {{> Template.Flow region=top}}
  {{> Template.Flow region=main}}
</template>
```

The `Flow` showcases the name of your Flow stuff. And "region" might make more grammatical sense.

**Comment by elidoran** [comment]
@trusktr It's in Meteor core: [{{> Template.dynamic}}](http://docs.meteor.com/#/full/template_dynamic)

I agree 'region' seems a better name for it. It's referencing a template to include by name and getting that name reactively, so, it also makes sense for it to be called 'template'.

**Comment by trusktr** [comment]
Oh, gotcha. I don't know enough meteor yet. xD

**Comment by trusktr** [comment]
Thanks!
