### ISSUE TITLE
The template part stays after route change

### ISSUE THREAD

**Issue by VladShcherbin** [meteorhacks/flow-layout#14]
Currently, if you have a layout with two parts:

```js
{{> Template.dynamic template=columnOne}}
{{> Template.dynamic template=columnTwo}}
```

Then, in routes you can specify
**first route**

```js
FlowLayout.render('adminLayout', {columnOne: 'adminOrders', columnTwo: 'adminOrders'});
```

**second route**

```js
FlowLayout.render('adminLayout', {columnOne: "adminDashboard"});
```

So, second route does not have the **columnTwo**. If you go from 1 to 2 route - the *columnTwo* will stay the same, *adminOrders* - it does not flush. To force flush, we need to run:

```js
FlowLayout.render('adminLayout', {columnOne: "adminDashboard", columnTwo: null});
```

Is it supposed to work that way or it has to check for provided parts and flush the old ones?

**Comment by delgermurun** [comment]
I think it's right way.

**Comment by arunoda** [comment]
Yes. It's the correct way. You need to explicitly mention.

**Comment by VladShcherbin** [comment]
@delgermurun , @arunoda okay, thank you guys
