### ISSUE TITLE
Not re-rendering child template

### ISSUE THREAD

**Issue by DEfusion** [meteorhacks/flow-layout#15]
I have the following routes:
```
FlowRouter.route '/',
	action: ->
		FlowLayout.render('basicLayout', {main: 'home'})

FlowRouter.route '/seasons/:season/episodes/:episode',
	action: ->
		FlowLayout.render('basicLayout', {main: 'episode'})
```

My home template consists of this:

```
<template name="home">
	{{> episode episode=latestEpisode}}
</template>
```

And my episode template contains the episode. The episode template isn't being re-rendered as I would expect with this setup, I noticed at first as the data wasn't updating and added debugging to `rendered` and it only fires on first page load not route changes.

I doubly confirmed this by adding this helper and outputting it in the episode template:

```
Template.episode.helpers
    random: ->
		Math.random()
```

The child data for the episode (games) is updating as expected though.

**Comment by arunoda** [comment]
It's hard to answer by looking at these since I don't have the template for the layout.
It's great, if you can create repo which has this issue and send me that.
Then I can look at it.

**Comment by DEfusion** [comment]
Sorry I realised it is working as expected and the issue was with the way I was originally handling the data in my episode template (currently migrating from iron router). Thanks for your response sorry for the false bug report.

**Comment by arunoda** [comment]
No problem.
