### ISSUE TITLE
FlowLayout strips protocol from data

### ISSUE THREAD

**Issue by mbabauer** [meteorhacks/flow-layout#17]
I am new to FlowRouter and FlowLayout, but it seems like FlowLayout is stripping my protocols out of my objects.

I like to follow a pattern for my collections like this:
```javascript
MyObject = function(doc) {
  if(doc) {
    this._id = doc._id;
    this._myVal = doc._myVal;
};
MyObject.prototype = {
  get id() {
    return this._id;
  },
  get myVal() {
    return this._myVal;
  },
  set myVal(value) {
    this._myVal = value;
  },
  save: function() {
    var that = this;
    doc = {
      myVal: this._myVal
    };
    if (!this._id) {
      that._id = MyObjects.insert(doc);
    } else {
      MyObjects.update({_id: this._id}, {$set: doc});
    }
  }
};
MyObjects = Meteor.Collection('my_objects', {
  transform: function(doc) {
    return new MyObject(doc);
  }
});
```

It's a little verbose, but it allows me to contain the values and methods as if they were an entity, which I find easier in my coding.  However, when I do something like this:
```javascript
FlowRouter.route('/myObject/:id', {
  name: 'pageEditPermalink',
  action: function(params) {
    FlowLayout.render('MasterLayout', 
      { main: 'myObjectViewer', data: MyObjects.findOne({_id: params.id}) });
  }
});
```
And then in my layout this:
```
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<template name="MasterLayout">
    {{> header }}
    <div class="yield_container">
      {{outputThis}}
      {{> Template.dynamic template=main data=data}}
      {{> footer }}
    </div>
</template>
```
All of the prototype getters/setters/functions are stripped out of the data object.  I have added a console.log to the route to output the results of the `MyObject.findOne()` and it does have the getters/setters/functions in the prototype.  I believe it's getting stripped out here (or, I should say, this is where I first see the data w/ the prototype stripped):
```javascript
FlowLayout._buildRegionGetter = function _buildRegionGetter(key) {
  return function() {
    return currentRegions.get(key);
  };
};
```
But I don't know why the version of the object there has the prototype stripped out.  How can I pass my object in without it being stripped like that?

**Comment by arunoda** [comment]
Here's the issue:

~~~js
FlowRouter.route('/myObject/:id', {
  name: 'pageEditPermalink',
  action: function(params) {
    FlowLayout.render('MasterLayout', 
      { main: 'myObjectViewer', data: MyObjects.findOne({_id: params.id}) });
  }
});
~~~

Don't send the whole object via data. It's meant to be send a small piece of data. 
Send only appId. (or don't send it at all, use `.getParam()` API)

We are using a ReactiveVar behind the scene and it's strip out all the functions. (Which is needed)

**Comment by mbabauer** [comment]
Ok, so just to make sure I understand I should only be sending the _id (or some other identifying information) through FlowLayout?

**Comment by arunoda** [comment]
yes. exactly.

**Comment by mbabauer** [comment]
Thanks, closing the issue...
