### ISSUE TITLE
Why do we need #__flow-root

### ISSUE THREAD

**Issue by VladShcherbin** [meteorhacks/flow-layout#2]
Hi, @arunoda 

Why do we need the div#__flow-root ? It looks very ugly, can we please get rid of it?

Maybe we can use the body tag or is there a reason for this div?

**Comment by arunoda** [comment]
I don't like adding it to the DOM directly. We may need to stay inside a
DOM.
We can have a better name for sure.

**Comment by VladShcherbin** [comment]
@arunoda yep, we can change the name, but the element would be still kind of a 'wrapper'. 
Can't just use the `body` element or is it *necessary* to have an element inside the body?

**Comment by arunoda** [comment]
Yes it is. We need to flow layout to work with others nicely. I don't wanna
put everything into body.

**Comment by VladShcherbin** [comment]
@arunoda oh, okay, I'll use `body` in my projects then.
