### ISSUE TITLE
_getRootDomNode runs before <body> template inserted into document

### ISSUE THREAD

**Issue by fightingtheboss** [meteorhacks/flow-layout#25]
I've just upgraded to the latest version of `flow-router` (1.16.1) and now I'm having a very basic problem. I have a template that sets my overall site layout inside a `<body>` tag, then I use `FlowLayout.setRoot('main')` to target the element I want to render my layouts inside of. This was working fine with `flow-router` (1.9.0), but now it seems that it `FlowRouter._getRootDomNode` is called before the body template is inserted, or something is causing that initial template to be cleared out.

```html
<!-- /client/body.html -->
<body>
  <header>LOGO</header>
  <main></main>
  <footer></footer>
</body>
```

```html
<!-- /client/layouts/app-layout.html -->
<template name="appLayout">
  {{> Template.dynamic template=main }}
</template>
```

```js
// /client/layouts/app-layout.js
FlowRouter.setRoot('main');
```

```js
// /lib/router.js
FlowRouter.route('/', {
  name: 'root',

  action: function(params, queryParams) {
    console.log('Showing home page');
    FlowLayout.render('appLayout', { main: 'feed' });
  }
});
```

*Result*
```
Error: Root element does not exist
    at Object._getRootDomNode (layout.js:92)
    at layout.js:12
    at Object.Meteor.startup (startup_client.js:63)
    at Object.render (layout.js:11)
    at FlowRouter.route.action [as _action] (router.js?208806fd262b2b20e3e6a2bef0b15ca6bb5ad678:25)
    at utils.js:191
    at runMiddleware (utils.js:191)
    at Route._processMiddlewares (utils.js:191)
    at Route.callAction (utils.js:191)
    at utils.js:191
```

I've tried to debug this on my own but haven't sorted it out yet, so I figured I'd ask, just in case I'm doing something totally wrong.

**Comment by elidoran** [comment]
After your first mention of `FlowLayout.setRoot` your refer to using `FlowRouter.setRoot` twice, even in your code example. I know you mean the former, just pointing it out for anyone who doesn't notice it right away.

I checked and I get this error in versions 1.16.x, but not in 1.14.0 and 1.15.0. The `$(root)` part doesn't return a real DOM element so its `get(0)` call returns undefined. I can then run `FlowLayout.render()` from the browser console and it works fine.

**Comment by fightingtheboss** [comment]
Thanks for testing with the other versions. I tried to follow through the logic flow to figure out where the problem occurs, but I ran out of time. Will revisit when I've got a moment.

My current hunch is that the `FlowRouter.render` is somehow ending up on the `Meteor.startup` queue before the `Template.body.renderToDocument` is getting on there.

**Comment by arunoda** [comment]
Hmm. Good Idea. We may need to it at the end of the Meteor.startup. That'll fix this. I'll give this a try to fix it today.

**Comment by fightingtheboss** [comment]
Thanks for looking into this @arunoda. I made a very simple app that reproduces the bug that could possibly be of some help to anyone investigating this further.

https://github.com/fightingtheboss/flow-router-body-template-test-case

**Comment by fightingtheboss** [comment]
So this problem basically prevents you from using `.setRoot`. I dove deeper but none of my solutions yielded a satisfactory result. I thought about binding the `FlowLayout.render` to `Template.body.onRendered`, but that broke all the tests and is limiting in the general case where you don't have DOM nodes you want to render to on the body template.

The best solution would seem to be somehow delaying the `FlowRouter.initialize` (moving it further down in the `Meteor.startup` queue) or the `FlowRouter.render` until after `Template.body.onRendered` is called, but I don't know how to control that load order specifically in the general case. I guess if the app was built with the "everything is a package" paradigm, you could define the load order.

The workaround for now is to avoid `.setRoot`, don't put DOM nodes in the body template and have a "parent" layout for the shared chrome for your app.

Thoughts?

**Comment by arunoda** [comment]
@fightingtheboss I think we can fix with without user involvement. @pahans  Just did a fix(see above) on the and I merged. 
Can you check this with the master branch of flow-layout. 
If it solves your issue. I can do a release.

**Comment by fightingtheboss** [comment]
Looks good to me! I forgot that `Meteor.defer` is essentially a `setTimeout` of 0, so it can be used on the client to move calls to the end of the event loop. Thought of it mostly as a backend trick. A valuable lesson, thank you!

Thanks for the fix, @pahans

**Comment by arunoda** [comment]
Great. I will do a release.

**Comment by arunoda** [comment]
Released a  new version `1.4.1`

**Comment by victorkurauchi** [comment]
hi. i'm using the version kadira:blaze-layout@2.0.0 and kadira:flow-router@2.3.0 

While trying the app, i faced the same error. In this version, something changed ?

    BlazeLayout.setRoot("main");

    FlowRouter.route('/', {
      action: function(params, queryParams) {
        BlazeLayout.render("dashboard", { main: "dashboard_main_content" });
      }
    });

Thank you in advance.
Best regards.

**Comment by quietcreep** [comment]
@victorkurauchi Looks like you need a selector tag ('.' for class or "#" for id attributes).  Did you try doing 
``` javascript
BlazeLayout.setRoot("#main");
```

If that doesn't solve it, did you remove the "meteor-platform" package? I had the same issue, so I followed the trace back to a jQuery function call; I had removed the meteor-platform package, removing jQuery along with it.
