### ISSUE TITLE
No events and onRendered callback on Template.body

### ISSUE THREAD

**Issue by gabrielalmeida** [meteorhacks/flow-layout#27]
Hi,

I don't know if this is the expected behavior, but ```Template.body.onRendered``` will run only if there is a ```<body>``` tag somewhere. Although in some cases there is no need to exist a body tag, as ```Flow Layout``` will append root layout to it.

While it sounds inconsistent to have ```body``` rendered on screen and ```Template.body.onRendered``` not being called, perhaps it's just a ```bad practice``` on my side not to include a ```body``` tag with FlowLayout :smile:

But, in the case of events, independent of the existence of a ```body``` tag, they will never be fired.

Obviously we can circumvent this by listening to ```Template.layout``` instead of ```Template.body``` or through ```jQuery``` for ex., but then there is no way to have _catch all_ ```events```, or there is?

Reproduction repo:
[gabrielalmeida/flow-layout-onRendered-and-no-events-reproduction](https://github.com/gabrielalmeida/flow-layout-onRendered-and-no-events-reproduction)

Maybe everything above is the expected behavior, but at least for me it's somehow confusing, I would always expect the following, which I believe is the Meteor default(albeit vanilla Meteor will always require a ```body``` tag):

When this happen | this is expected behavior
------ | -------------
DOM element ```body``` is rendered on screen w/ or without ```body``` tag on a ```.html``` | ```Template.body.onRendered``` will be called (always will be)
Element is inside ```body```(always will be) | It will always listen to events applied on ```Template.body``` if selector matches

This issue is more a sort of report to warn unaware people about those behaviors.. The only final caveat I can see is: No way to ensure you're listening to events on **ANY** element on a page with Meteor Events API while using FlowLayout.

Thanks

**Comment by arunoda** [comment]
That's possible since, we don't Meteor create a body tag ourselves using
flow and we use jquery to insert it.
May be we can ship a body tag with flow-layout, but I don't feel that's
necessary.

**Comment by gabrielalmeida** [comment]
Yep, I agree that it doesn't seem to be a necessary modification as everything can be easily avoided.

I stumbled upon on this while using multiple layouts and trying to apply catch-all event listeners across all of them, but I don't think it's a common approach and also obviously not a good one.

I can't imagine other error-prone situations that may occur because of the behaviors listed above..

But it's easy to forget a body tag while using FlowLayout and then don't realize that you just missed it :stuck_out_tongue_closed_eyes:

**Comment by arunoda** [comment]
Anyway, thank for putting it here. May be it'll help someone.
I hope google will index this page for  us :)

**Comment by gabrielalmeida** [comment]
That was the main reason I did it.
Pretty sure google will index here, github doesn't lack SSR hehe :)

Thank you for this and all other great packages you maintain!

**Comment by arunoda** [comment]
ha ha.Yeah! It does SSR :)
