### ISSUE TITLE
No render on route change

### ISSUE THREAD

**Issue by stephan281094** [meteorhacks/flow-layout#28]
Hello there. I'm not sure whether to post this in flow router or flow layout. Anyway:
I set up the following route (with Flow router):
```js
FlowRouter.route '/:username',
    action: ->
        FlowLayout.render('layout', {content: 'profile'})
    name: 'profile'
```

When I go to `/john` and click on a link going to `/jane`, my content doesn't change. However, when I refresh it **does** change. I'm guessing FlowLayout only renders if it has to render a different template or when forcing a re-render?

I can't imagine this being a bug, so what am I doing wrong?

Btw, I am using autopublish.

**Comment by arunoda** [comment]
We need templates as well. Better if we can get a sample repo to test out.

**Comment by stephan281094** [comment]
Hi Arunoda. Thank you for replying so quickly.

I created a sample repository which you can see [here](https://github.com/stephan281094/flow).

**Comment by stephan281094** [comment]
For your convenience I deployed it [here](http://flowlayout-iss28.meteor.com/).

**Comment by arunoda** [comment]
@stephan281094 I can see the problem. Let's see what's going on here.

**Comment by arunoda** [comment]
Check this line: https://github.com/stephan281094/flow/blob/master/client/profile/profile.js#L4

`FlowRouter.current()` is not reactive. See FR docs :)
Replace it with this: `FlowRouter.getParam('username')`

How do you wanna use use `FlowRouter.current()` when we've some APIs.

**Comment by stephan281094** [comment]
Awesome! Works like a charm.
Thank you.
