### ISSUE TITLE
version 1.4.2 breaks my app

### ISSUE THREAD

**Issue by jononomo** [meteorhacks/flow-layout#34]
So with version 1.4.1 my app behaves as expected.  With version 1.4.2 I see a problem.

I have the following code in my app:

```javascript
render_modal = function(modal_template) {
    FlowLayout.render('layout', {
        modal: modal_template
    });
    Meteor.setTimeout(function() {
        Session.set('modal', true);
    });
}
```

elsewhere (in `client/autorun.js`) I have this:

```javascript
toggleModal = function() {
    if (typeof Session.get('modal') !== 'undefined') {
        if (Session.get('modal')) {
            showModal();
        } else {
            hideModal();
        }
    } else {
        Session.set('modal', false);
        toggleModal();
    }
};
Tracker.autorun(toggleModal);
```

When the user takes certain actions my code will react by calling `render_modal` and passing the name of the template to render.  The expectation is that FlowLayout will change the template that is rendered in the "modal" section, but will not touch anything else.

Elsewhere in my app (in my flow-router section, actually) I have the following:

```javascript
FlowLayout.render('layout', {
    left_nav: 'audit_nav',
    main: 'audit',
});
```

My expectation is that the `left_nav` and `main` sections should not be affected if I make the following call:

```javascript
FlowLayout.render('layout', {
    modal: modal_template
});
```

With version 1.4.1 this expectation is met.  However, with version 1.4.2 when I make this call I find that `left_nav` and `main` sections become blank.

In case you are curious, my `layout` template is as follows:

```html
<template name='layout'>
  <div id='my-left-nav-wrapper'>
      <div id='my-left-nav'>
         {{> Template.dynamic template=left_nav}}
      </div>
  </div>
  <div id='my-main'>
      {{> Template.dynamic template=main}}
  </div>
  <div id='my-modal-background'></div>
  <div id='my-modal-wrapper'>
      <div id='my-modal'>
          {{> Template.dynamic template=modal}}
      </div>
  </div>
</template>
```

**Comment by arunoda** [comment]
Actually, you are using a bug of FlowLayout as a feature.
What you describe is a bug. If you not set the data, previous values should gets empty.

But, I've a better solution for your case.

Write a template helper for the above template to get the modal name. Then inside that helper, you FlowRouter apis like, `.getQueryParam()` or `.getParam()` to return the right template.

**Comment by jononomo** [comment]
Thanks - I have adopted your improved solution.
