### ISSUE TITLE
Where do I set up <head> element using flow layout?

### ISSUE THREAD

**Issue by 416serg** [meteorhacks/flow-layout#35]
```
<template name="layout">
  <head>
    <title>Raise your flag</title>
    <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
    <link rel="icon" sizes="16x16" href="/favicon.ico?v=2">
  </head>
  <body id="page-top">
    {{> sAlert}}
    {{#momentum plugin='flow-router'}}
      {{> Template.dynamic template=top}}
      {{> Template.dynamic template=main}}
    {{/momentum}}
  </body>
</template>
```
this doesn't seem to work

**Comment by arunoda** [comment]
In meteor we can't have dynamic heads and do it inside templates.

To create a head, create another HTML page and add the head.

**Comment by 416serg** [comment]
so i create a `head.html` with `<head></head>` and that's it? no need to mention it anywhere in the flow router/layout>

**Comment by elzii** [comment]
@416serg How did you solve this?

**Comment by sergical** [comment]
@elzii create a `head.html` file containing the `<head></head>` element and the app should pick it up. If you want to set individual route's SEO use the <a href="https://github.com/kadirahq/meteor-dochead">Dochead</a> package
