### ISSUE TITLE
Components not being switched. 

### ISSUE THREAD

**Issue by fxv** [meteorhacks/flow-layout#5]
Hi,
I have the following code in my route.js file
<pre><code>
FlowRouter.route('/', {
    action: function(params) {
        FlowLayout.render("mainLayout", { top: "header", main: "postsList" });
    }
});

FlowRouter.route('/posts/:_id', {
    action: function(params) {
        FlowLayout.render("mainLayout", { top:"header", main: "postPage" });
    }
}); 
<code></pre>

However, when in /posts/:_id, 'postPage' is rendered on top of 'postsList'. I'm using FlowLayout and React.

**Comment by arunoda** [comment]
I'm quite clear on what's going here. May be you can send me some sample code.

**Comment by fxv** [comment]
Hi Arunoda. Here's some code from a microscope sample app with flow-layout and reactjs:
https://github.com/fxv/microscope
Thank you for looking into this.

**Comment by arunoda** [comment]
Okay. I will have a look at this.

**Comment by arunoda** [comment]
Seems like you are directly trying to use react components as templates.
Frankly, I'm quite not sure how it works.

If you wanna use react, you can simply render them inside the flow-router's action callback.

**Comment by fxv** [comment]
That works. It may be an issue with how I 'm using <code>reacts:react-meteor</code>, which allows you to include a React component into a Blaze template if you assign it the property <code>templateName:</code>
