### ISSUE TITLE
'ui' package is deprecated 

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-layout#7]
Since it released after 1.0, how about replacing with it `blaze`? Or do you have project on 0.9?
`flow-component` also uses `ui` package.

**Comment by arunoda** [comment]
Okay sure. I'm okay with that. Send me a PR.

**Comment by delgermurun** [comment]
@arunoda How about `api.versionsFrom(METEOR@0.9.2)`? I don't know how it effects project. But it looks little weird :), since we are all using 1.0.

**Comment by arunoda** [comment]
Yes. Use 1.0. That's fine.
I got this from a old repo.
